Submitty/submitty.github.io

_docs/developer/configurating_tie_in_programs.md
Added the new page "configuring tie in programs." The page is meant to be used as a space to describe special configuration steps for getting 3rd party programs (e.g. Matlab) to work with Submitty.
=> Added Matlab Development Documentation.

_config.yml
Although seemingly minuscule, rearranging the order of options in the `_config.yml` seems to fix a bug where spaces appear at the front of each line in a codeblock.
=> Fix for spaces in front of code blocks

_layouts/default.html
While reading docs, I noticed that I have to scroll sidebar every time I move to the next page (It is especially annoying when you reading the last section "Developer")
Possible solution, one that I've implemented, might be to change offset of the sidebar in Javascript (in the section where 'current' class is assigned to list element)
Tested on my local machine in Google Chrome v65.0.3325.181
Drawbacks:
1. Sidebar is loaded before script is executed. This causes "flickering" of the sidebar when page is loading
=> Auto-scrolling sidebar to current section

_sass/_layout.scss
Right now, it's hard to tell what page you're on in the sidebar (especially if you scroll it). This should make it more visually distinctive by bolding the link. This does not affect the styling on the parent element within the sidebar.
=> Make link for current page in sidebar more distinct

_docs/developer/index.md, _docs/grader/index.md, _docs/index.md, _docs/instructor/index.md, _docs/student/index.md, _docs/sysadmin/index.md, _layouts/default.html, _sass/_layout.scss, css/main.scss, scripts/main.js
The next step of improving the sidebar readability.
If you're within a section, then the section is expanded, else it is collapsed. If you click the arrow next to the top-link that has children, it will expand/collapse the section as appropriate.
* Moves the setting of the current tag into the HTML layout which is quicker/better than using javascript
* Move the "auto scroll" for the sidebar into 'load' eventListener (which fires after all CSS and such is loaded, unlike DOMContentLoaded which fires just when all DOM is inserted) to improve reliability of this feature
* Adds anchor svg on header tags within content that show up when hovering over the header which when clicked presents you the hash of the element into your browser window making it easier to copy/paste those elements. …
=> Add collapsable sidebar of top links

_docs/instructor/assignment_configuration.md
The instructor documentation reflects that possible values for a testcase type include "compilation", "file_check", or "execution".
However, the source code reflects possible values of "Compilation", "FileCheck", or "Execution", with "Execution" being the default value.
=> Updating possible values for testcase type

_docs/sysadmin/server_os.md
Closes Submitty/Submitty#2118 adding an official policy of what distros we support and when we drop support (mainly just the latest Ubuntu LTS and that support for prior version will be dropped after one full academic year, all other distros are at our discretion).
I also removed a lot of the other writing as it was kind of just noise that doesn't really make sense to have within our installation docs (e.g. the section on recommending people turn on automatic updates, proxying, keyboard to use, etc.) which are either largely common sense or something a sysadmin should know or not really in any detail that an absolute beginner would understand the terminology or what they'd be looking for.  I think just pruning it to be just stuff relevant to Submitty is the way to go.
=> Update server OS to list supported platforms and deprecation policy

_data/links.yml
I found the link to [Discussion Forum](https://submitty.org/instructor/forum) in Gagan Kumar's GSoC report, but I can not find it in the sidebar. Not sure if it is intentionally hidden though.
=> Show doc for Discussion Forum

_docs/instructor/log_files.md
Now log_files.md is put under "Instructor" category while the category shown in the [webpage](https://submitty.org/instructor/log_files) is "Developer".
=> Correct the category of Log Files

_docs/sysadmin/installation.md
The bootstrap branch no longer exists, which leads to 404 error. Fixed by replacing the link.
=> Fix link 404 Error

_docs/developer/end_to_end_tests.md
Clear and concise documentation of the installation of ChromeDriver is not available on the website linked for ChromeDriver. I was using it for the first time and got fairly confused, having use an external blog to understand its installation process. It will help users to have it here. They keep changing the version numbers and there's no 'latest' release directory, thus the user may have to write the latest download's URL/version number himself.
=> Include installation of ChromeDriver on Linux

_docs/developer/vm_install_using_vagrant.md
Changed table on Step 11 from the "VM Install using Vagrant" markdown file (https://submitty.org/developer/vm_install_using_vagrant). Before, the users were not in any particular order, nor were their purposes differentiated. Trying to log on to Submitty using the root or vagrant account, for example, would not work. The updated table displays the users and passwords (organized by category) as well as their role in the VM environment.
Furthermore, the numbering after 10 was formatted incorrectly; the file now displays the proper indentation and numbering.
Fixed some lines according to markdown standard practice.
=> Clarified VM Install Instructions

_docs/sysadmin/server_os.md
Documentation update for Submitty/Submitty#3625
=> Officially deprecates xenial and jessie distros

_docs/developer/phpstorm.md
Added a message to the xdebug portion of the PhpStorm developer documentation that informs the user that they will probably receive an error message but it can be safely disregarded.
=> Added documentation to xdebug PhpStorm docs

_docs/developer/automated_grading.md
Setup folder contains following files and folder:-
Config folder contains following files and folder:-
autograding_workers.json is contained only in config and path described in documentation shows that it is contained in .setup folder
=> Incorrect Directory for autograding_workers.json

_docs/developer/migrations.md
> Thus, it is important to ensure that the `up` migration can be re-run.
I thought it meant: We should ensure that `up-up-up-up-up` is successful.
However, according to Matt at https://github.com/Submitty/Submitty/issues/3769#issuecomment-498909911, it actually means: We should ensure that `up-down-up-down-up` is successful.
=> Modify the wording of up migration re-running

_docs/developer/vm_install_using_vagrant.md
Changed vm_install_using_vagrant.md file to include am alternative way to ssh into vm when vagrant ssh asks for root password.
=> Alternative to vagrant ssh to be included in submitty install file

_docs/developer/php_unit_tests.md
Went through the steps to get php unit tests working on a clean install (on debian 9 'stretch') 
Changes:
PHPUnit refused to work on anything other than 7.2 or 7.2 so thats updated in the docs
Submitty tests moved from the root directory to Submitty/site
Composer couldn't run without some packages which are now listed
Xdebug is required as a code coverage driver 
Added some packages if PHPUnit fails on the first time
=> Updated instructions for installing and running php unit tests

_docs/instructor/assignment_configuration.md
In reference to Submitty/Submitty#3164, adds documentation that some RLIMIT values will have a minimum that is set and must be used regardless of the configuration value.
=> Document minimum RLIMIT values for certain testcase types

_docs/instructor/create_edit_gradeable.md
Changes the section of documentation in instructor/Create or Edit a Gradeable from "Grading by Registration Section or Rotating Section" to "Grader Assignment Method" and added information about all access grading.  
Changes are related to pending PR #3872 (in Submitty repo), so should be merged after that change.
=> Changed Grader Assignment Method to include All Access

_docs/sysadmin/email_configuration.md
change email configuration documentation to tell sysadmins to use CONFIGURE_SUBMITTY instead to change email so defaults do not get out of sync 
goes with PR Submitty/Submitty#3922
=> sysadmin email configuration use CONFIGURE_SUBMITTY

_docs/sysadmin/installation.md
Updated documentation for Submitty/Submitty#3356 / Submitty/Submitty#4091 on how to modify the default HTTP configuration to use SSL. The SSL details can be automatically done by either Let's Encrypt or manually inputted/told to you by whoever you get your SSL certificate from/institute's sysadmin.
=> Update the apache setup details to discuss setting up SSL

_docs/developer/development_instructions.md
Added documentation to help developers figure out how to pause and unpause the time sync and change it to whatever they want.
=> Documentation for Changing Site Time in Vagrant

_docs/sysadmin/system_customization.md
As discussed before, instead of increasing the default max number of files that can be uploaded at once from 20 to 100, write documentation for sys configs to change the value
=> Add sysconfig instructions to increase max file upload size

_docs/developer/php_unit_tests/writing_unit_tests.md
Expands existing documentation for writing PHP unit tests adding some more details, and clarifying wording in some places. I've also updated all links to PHPUnit docs to use `latest` which should always point to the version we currently use(which is `8.3` right now).
New sections:
* Mocks / Test Doubles for classes and PHP builtin functions
* Data Providers
Added words for:
* That technically, need to expand off `\PHPUnit\Framework\TestCase`, but that `BaseUnitTest` may be beneficial to use (people should not cargo cult using it if they do not need it).
* description of class level setup and teardown
* the `--filter` flag for running specific test functions or classes
* requirements for generating code coverage (xdebug or pcov)
=> [Documentation:Testing] expand docs for writing php unit tests

_docs/developer/migrations.md
When looking over the migration docs I tried to run the line `sudo python3 /usr/local/submitty/GIT_CHECKOUT/Submitty/migration/migrator.py -h` however that file was not found. I could be wrong (I am new to this which is why I was reading the docs) but I think it should have been run_migrator.py not migrator.py. The command above on the page does use run_migrator.py and it works.
=> [Documentation:Migrations] Changed typo from migrator.py to run_migrator.py

_docs/developer/json_configuration_files.md
The path to get to the course data seems to be missing `/courses` in it
On my local version of submitty the path is `/var/local/submitty/courses/f19/` however the docs have it as `/var/local/submitty/f19/`
=> [Documentation:JSON Configuration Files] added missing /courses to path

_docs/developer/coding_style_guide/php.md
The name in the docs was "Submitty" but in the linter the standard is named "SubmittyStandard"
=> Fixed name of standard in linter package

_docs/developer/coding_style_guide/php.md
There was some internal discussion at RPI about how to get this line working. Adds a note above about using `composer install` to just do this, though points at the relevant wiki page at phpcs if someone wants to learn how to do it manually.
=> add note about running composer install to install/setup phpcs

_docs/developer/development_instructions/vagrant_email_configuration.md, _docs/sysadmin/email_configuration.md
The json files had "true" as a string when it should have been true. Also one file was missing true to begin with.
=> Fix type of config field email_enabled in docs

_docs/developer/php_unit_tests.md
The page for e2e test should not have .md on it.
[https://submitty.org/developer/end_to_end_tests.md](https://submitty.org/developer/end_to_end_tests.md) fails
[https://submitty.org/developer/end_to_end_tests](https://submitty.org/developer/end_to_end_tests) works
=> [Bugfix:url] Fixed broken url for e2e tests

_docs/developer/development_instructions/vagrant_email_configuration.md
This adds instructions for how to start and enable nullsmtpd for people that dont use linux very often and might now know how systemctl works.
=> [Documentation:Developer] Added instructions on how to start nullsmtpd

_docs/developer/vm_install_using_vagrant.md
This adds a reminder for new developers that they may want to fork the repo. I know this is common sense for a lot of us but for new developers, especially from gsoc, who we do not want to add to the Submitty github organization this will help remind them to use a fork. 
Somebody had this issue on slack and while it is not too hard to solve, I think having this reminder  could reduce the likelihood for this kind of problem going forward.
=> [Documentation:Developer] Added a reminder to fork the repo for new devs

_docs/student/discussion_forum.md
Updated the markdown documentation to add bullets, reformatted it a bit.
Images can be added using (very weird) syntax, but I didn't add it into the documentation since attachments should probably be used instead (when adding images in, I didn't see a way to change the size of the image when displayed)
=> Updated markdown documentation

_docs/developer/vm_install_using_vagrant.md
The two links to VirtualBox and Vagrant were broken.
=> [Docs:Developer] two links

_docs/developer/coding_style_guide/php.md
Adds description / words about type declarations in PHP. This is increasingly the "best practice" of writing PHP code as it makes it safer to work in the code base and increases the power of static analysis tools like phpstan.
=> [Documentation] Add details about type declarations for PHP

_docs/developer/updating_dependencies.md
Rewrites the section to be reflective of what's going on as we've moved away from using scripts to maintain all of those dependencies, and now use composer / npm for it all.
=> [Documentation] Rewrite section on third-party dependencies

_docs/developer/migrations.md
sister PR to Submitty/Submitty#5392
Adds two commands to the migrator docs to run to get the updated sql file from a result of using `pg_dump`. This simplifies the process of things for a developer of updating these files, and will make sure that this file is always uniformly designed.
=> [Documentation] use pg_dump for migrator sql

_docs/instructor/rainbow_grades/iclicker_instructions.md
Closes Submitty/Submitty#1580
Made some significant changes to the wording about supported versions, a few other minor tweaks, and added the `earned_late_days` field in.
Also importantly Updated iClicker documentation to be consistent with 2018 onwards which has expected `file` to be an array (yes, we still called it `file` instead of `files` in Rainbow Grades). I got some nasty looking errors when I tried without making it an array (due to how the Python script that looks to see if there's XML files that need scooping up works).
=> iClicker Documentation Updates

_docs/developer/testing/index.md
The current mentioned php-sqlite install causes the code to break in initial setup and does not process with composer install. The reason for this might be php sqlite is obsolete and is replaced by php-sqlite3
=> Update php-sqlite to php-sqlite3 for Ubuntu setup

_layouts/default.html
Adds a meaningful aria-label attribute to the search input to assist screen readers to know what the input is for. I've removed the title attribute as I do not think it's valuable and if functionality is confusing would say just update the placeholder to be "Search submitty.org" or something.
Closes Submitty/Submitty#5552
=> Replace search input title with meaningful aria-label

_docs/developer/coding_style_guide/php.md
From review on Submitty/Submitty#5660, I realize that there's no discussion of strict typing in the code style document for PHP. This PR adds such a section.
=> Add note about strict typing to PHP coding style

README.md
The README had some outdated information on navigation and such that would be relevant if we more closely followed the code of our original fork of Edition. This updates the words to hopefully be a bit more informative to new developers as well on creating pages, adding stuff to navigation, etc.
=> Clean-up README to be more informative

_docs/developer/automated_grading.md
PR #5676 in the main repo
https://github.com/Submitty/Submitty/pull/5676
moved the location of the submitty_autograding_worker.py and submitty_autograding_shipper.py files
=> [Bugfix:Documentation] update paths of shipper & worker

_docs/developer/coding_style_guide/javascript.md
Adds the rule to existing rules used for JS linting along with a description and its link
=> Add "curly" rule to javascript style guide

_data/links.yml, _docs/developer/testing/install_php.md, _docs/developer/testing/linting_static_analysis.md, _docs/developer/testing/php_unit_tests.md
Developer ran into trouble running php linter locally, did not have PHP installed on their system, adds documentation for it
Adds note for running on WSL which does not need the `php` command in front of the command for running php tools whereas linux and mac do.
=> Add documentation on installing PHP Locally 

_docs/developer/vm_install_using_vagrant.md
When running VirtualBox with Hyper-V installed, it forces VirtualBox to run with the Hyper-V backend. This can cause system instability inside of the VM, which can lead to unpredictable behavior which can be difficult to debug.
This adds a recommendation to disable Hyper-V, with a note to lookup how to add a separate boot entry should a developer want a way to quickly boot into Windows with and without Hyper-V enabled.
=> [Documentation:Developer] Add Hyper-V warning

_docs/developer/testing/site_end_to_end_tests.md, _docs/developer/vm_install_using_vagrant.md
Cask recently became an official part of the Homebrew project.  As such, it is no longer necessary to add `cask` when installing packages.
=> [Documentation:Developer] Use flag for brew cask installs

_docs/developer/developing_the_php_site/controller.md
Example controller under the "developing the PHP site" section was missing underscores for the `_semester` and `_course` which is required for the variable replacement to occur. 
Also 2 minor grammar fixes.
=> [Documentation:Developer] Fix controller example

_docs/sysadmin/worker_installation.md
Removes step changing directory into `~/.ssh` folder since it may not always exist. Instead, you can just `cd ~/` and run `ssh-keygen` which will make the folder if it doesn't exist, and if it does exist it will place the key in that folder.
=> [Documentation:System] Update Worker SSH Instructions

_docs/developer/json_configuration_files.md
Adds documentation on an a parameter that can be specified in the `config.json` for gradeables with autograding.
Since Submitty.org is in the middle of an overhaul and some of the instructor pages doesn't currently exist, I wasn't sure if there was a better place to add this (also given that some of the information on the modified page looked stale/not 100% verified). If necessary, this addition can be moved to a more appropriate spot.
=> [Documentation:Autograding] "release_hidden_details" parameter

_docs/developer/how_to_contribute.md
Adds calendar module to be introduced into the title checker in https://github.com/Submitty/action-pr-title/pull/6.
=> [Documentation:Developer] Add calendar module

_docs/developer/worker_vm.md
Adds documentation for how to create a VM-worker pair using `WORKER_PAIR=1 vagrant up`.
=> [Documentation:Developer] Add Vagrant Worker Pair Documentation

_docs/developer/developing_the_php_site/javascript.md, _docs/developer/developing_the_php_site/modules.md, navtreedata.js
The following PR adds documentation on how Submitty uses esbuild to bundle es6 and typescript files into our system.
https://github.com/Submitty/Submitty/pull/7285
=> [Documentation:Developer] esbuild for ES6 modules and TypeScript

_docs/sysadmin/version_notes/v21.11.01.md
https://github.com/Submitty/Submitty/pull/7320 includes changes to update the version of Node.js to 16.x.  This PR includes instructions for the upcoming 21.11.01 release of Submitty which will tentatively include this sysadmin action.
=> [Documentation:System] Add documentation for Node.js update

_docs/developer/coding_style_guide/php.md, _docs/developer/phpstorm.md, _docs/developer/testing/linting_static_analysis.md, _docs/developer/testing/php_unit_tests.md
Docs PR for https://github.com/Submitty/Submitty/pull/7303. The files have been moved so it's no longer necessary to specify the configuration file for running phpunit or phpcs.
=> [Documentation:Developer] Remove need to specify php conf files

_docs/developer/development_instructions/miscellaneous.md, _docs/sysadmin/installation.md
Basic documentation PR for https://github.com/Submitty/Submitty/pull/6482.
We may wish to create a new sysadmin page that specifically covers authentication methods as we LDAP here and think about adding support for CAS in the future. Thoughts @bmcutler?
=> [Documentation:System] Update docs to mention LDAP

_docs/developer/getting_started/vm_install_using_vagrant.md
This PR adds a second note under the VirtualBox install pre-check list and notes that using WSL2 may cause Hyper-V or Windows Hypervisor Platform to run and cause issues when using Virtualbox and recommends not using it if installing Virtualbox
=> [Documentation:Developer] Add WSL2 virtualbox specific warning

_docs/developer/software_and_system_design/coding_style_guide/php.md, _docs/developer/software_and_system_design/coding_style_guide/python.md
This PR updates the listed minimum version for PHP (`7.2` -> `7.4`) and Python (`3.6` -> `3.8`) since we've dropped support for Ubuntu 18.04 as part of https://github.com/Submitty/Submitty/pull/7925, and these are the versions of those languages included in Ubuntu 20.04.
=> [Documentation:Developer] Update minimum version for PHP/Python

_docs/developer/getting_started/vm_install_using_vagrant.md
Vagrant now natively supports Linux, so https://vagrant-deb.linestarve.com/ is no longer necessary. 
I have updated the link to show Vagrant's official download link. I have kept the old link in case it would be needed.
=> [Documentation:Developer] Updated Vagrant Link for Linux

_docs/developer/getting_started/vm_install_using_vagrant.md
Pre-Installation Checklist states that 20GB of disk space should be available.  Current VM takes more than 61GB, and it slightly varies depending on OS.
=> [Documentation:System] Disk space update on VM install

_docs/instructor/autograding/specification.md
Add info on the instructor pages about max submission size config. It is currently only in the system admin area of the docs.
=> [Documentation:Autograding] Add max submission size

_docs/developer/getting_started/vm_install_using_vagrant.md, _docs/developer/getting_started/vm_install_using_vagrant_apple_silicon.md
Updates the header styling in the ARM Mac setup instructions page to fix duplicate rules and be more consistent with the other vagrant page. Moves up the notice in the other vagrant page.
=> [Documentation:Developer] Fix ARM Mac page styling

_layouts/default.html
The date in the footer is currently listed as 2014-2022.  After this PR, the end date will be updated automatically on any build and we should never have to make an annual year bump PR again.
=> [Documentation:Developer] Update date in footer

_docs/developer/development_instructions/troubleshooting.md, _docs/developer/getting_started/vm_install_using_vagrant.md
Added useful tip in the Installation troubleshooting for M1 or M2 users when they encounter the following error : 
"Vagrant cannot forward the specified ports on this VM, since they would collide with some other application that is already listening on these ports. The forwarded port to 1511 is already in use on the host machine."
=> [Documentation:Developer] Vagrant port error for Apple Silicon Mac

_docs/developer/development_instructions/troubleshooting.md
Updates documentation on using environment variables to override default forwarded VM ports.
* Directly updating vagrant file should not be recommended as it is a tracked file
* Must install the env plugin to use a .env file
=> [Documentation:Developer] Update VM Port Variable Docs

_docs/developer/getting_started/pgadmin.md
For some windows users, they need to set host name to "127.0.01" in order to connect to the Submitty database with pgAdmin.
=> [Documentation:Developer] Troubleshooting for pgAdmin

_docs/index/people.md
Barb's name is missing on the right.
=> [Documentation:Developer] add barb to summer 2019

_docs/sysadmin/configuration/course_archiving.md
Currently, [this documentation page](https://submitty.org/sysadmin/configuration/course_archiving) uses ``semester`` on database calls when it should use ``term``.
=> [Documentation:System] Update Course Archived Semester

_docs/developer/testing/linting_static_analysis.md
The PHP baseline command now suggests providing ``phpstan`` additional memory.
=> [Documentation:Developer] Update PHPStan Baseline Command

_docs/developer/testing/cypress.md
Changes: Added "If you are on WSL and run into an error, make sure you installed `node.js` on your desktop (Program Files) and not inside your local Submitty repository." in cypress.md (https://submitty.org/developer/testing/cypress)
WHY: I ran into a issue while installing cypress (I installed node.js in the wrong file) and this is to help others who might run into the same issue.
=> [Documentation:Developer] Fix WSL issue installing Cypress

_docs/developer/software_and_system_design/database_design.md
Currently, both the Database design page and the pgadmin setup instructions pages have instructions on how to set up pgadmin. However, the pgadmin setup instructions page is more detailed and provides better instructions. I've changed the database design page to link to the pgadmin setup instructions page rather than providing its own less detailed instructions.
=> [Documentation:Developer] Database page redirects to pgAdmin page

_docs/sysadmin/troubleshooting/system_debugging.md
updates the documentation regarding how to test submitty functions while the websocket connection is down.
originated from issue #9788, https://github.com/Submitty/Submitty/issues/9788
=> [Documentation:System] info regarding stopping nginx

_docs/developer/testing/linting_static_analysis.md
Documentation change associated with https://github.com/Submitty/Submitty/pull/9900.
=> [Testing:Developer] Add files to PHPStan config

_docs/developer/testing/linting_static_analysis.md
Detailed instruction on submitty test script and its current commands
=> [Documentation:System] php lint script documentation

_docs/developer/software_and_system_design/coding_style_guide/python.md, _docs/developer/testing/linting_static_analysis.md
Added documentation of how to use pylint to docs
=> [Documentation:Developer] Added python linter pylint to docs

_docs/developer/software_and_system_design/coding_style_guide/python.md, _docs/developer/testing/linting_static_analysis.md
We no longer use Travis CI, so the documentation has been mostly updated to no longer show our uses in Travis CI
=> [Documentation:Developer] Removed travis docs

_docs/student/communication/markdown.md
Markdown allows using two different sets of symbols for the same action (bold, italic, etc.) but needs the starting symbol and the closing symbol to be the same symbol, so no mix-and-matching is allowed.
=> [Documentation:System] Clarify opening and closing symbols need to match in Markdown

_docs/developer/getting_started/vm_install_using_vagrant.md
Added Fedora Linux/RHEL install instructions for vagrant and VirtualBox to the Submitty.org developer page, as well as a few common issues.
=> [Documentation:Developer] Fedora VM installation instructions

_docs/developer/getting_started/vm_install_using_vagrant.md, _docs/developer/getting_started/vm_install_using_vagrant_apple_silicon.md
This adds documentation for https://github.com/Submitty/Submitty/pull/9766
=> [Documentation:Developer] Add packaged VM documentation

_docs/instructor/assignment_preparation/index.md, _docs/instructor/assignment_preparation/upload_gradeable.md
This PR adds documentation on how to use the feature added in https://github.com/Submitty/Submitty/pull/10100.
=> [Documentation:InstructorUI] Upload JSON to create gradeable

.github/workflows/test.yml, _docs/sysadmin/configuration/registration_feed.md
Ruby tests are currently not making it pass Build Site on main. By downgrading the version, Ruby tests will successfully get past Build Site.
Ruby tests still won't pass on main until PR #590 is also merged.
=> [DevDependency] Downgrade Ruby to 3.0 in Workflows

_docs/sysadmin/configuration/registration_feed.md
A section link on the Registration Feed linked to section 4 instead of the correct section 3, causing a fail in the Ruby test. This PR updates the link to be correct so that the Ruby tests will pass.
Ruby tests will only pass after PR #589 is also merged.
=> [Documentation:System] Fix Broken Section Link

Gemfile
On my machine, the test server required json to be included in the gemfile in order to be run. I altered the Gemfile to include it. I would like people to try to replicate the issue to make sure it wasn't just a problem with me.
=> [Bugfix:System] Test server requires json

_docs/sysadmin/configuration/term_creation.md, navtreedata.js
I created a new file and added instructions for usage of the create_term.sh script to create a script. I added it to the top of the configuration section as that is likely the first thing that the sysadmin should be doing.
=> [Documentation:System] Term creation instructions

_docs/instructor/assignment_preparation/index.md
This PR adds documentation for downloading the JSON version of a gradeable
=> [Documentation:InstructorUI] Add download documentation

_docs/instructor/assignment_preparation/upload_gradeable.md
This PR adds documentation to go along with https://github.com/Submitty/Submitty/pull/10252, adding dates to the upload JSON functionality. 
It also fixes grade inquiries which had the incorrect name, and values as stated in https://github.com/Submitty/Submitty/pull/10188#discussion_r1513735920
=> [Documentation:InstructorUI] Add dates to upload

_docs/sysadmin/configuration/registration_feed.md
The registration feed's code has been audited and updated to be compatible through PHP 8.3.  The major change to documentation is removing INI option for `auto_detect_line_endings` from config as it has been deprecated in PHP since PHP 8.1.  Also, some minor style changes.
=> [Documentation:System] Registration Feed Update

_docs/instructor/autograding/docker_images.md, navtreedata.js
This PR adds a new page on instructions to create/edit Docker images. It also makes note of the DockerImagesRPI repo that RPI maintains.
=> [Documentation:Autograding] Docker Image Creation

navtreedata.js
The upload gradeable via json is a page under instructor/assignment_preparation but doesn't show up in the navbar  
it now looks like:
=> [Documentation:InstructorUI] Upload Gradeable missing navbar

_docs/developer/getting_started/commit_to_PR_from_fork.md, _docs/developer/getting_started/make_a_pull_request.md, _docs/developer/getting_started/review_a_pull_request.md, navtreedata.js
Adds documentation for how to pull, commit, & push to a PR made on a fork from an external contributor.
=> [Documentation:Developer] instructions for pushing to a fork

_docs/developer/getting_started/commit_to_PR_from_fork.md
This commit acknowledges external users may have changed the name of their fork from "Submitty" and guides developers on finding and using the fork name correctly
=> [Documentation:Developer] Account for changed name of fork

_docs/developer/getting_started/phpstorm.md
All these settings related to PHP are in a separate section in the latest PhpStorm, rather than under the Languages & Frameworks section.﻿
=> [Documentation:Developer] Update Advanced Setup Guideline

_docs/developer/getting_started/commit_to_PR_from_fork.md
add instructions to remove the upstream
=> [Documentation:Developer] unset upstream for fork PRs

_docs/instructor/course_settings/rainbow_grades/customization_basics.md
Complete the guide for the configuration of customization.json found in Instructor > Course Settings > Rainbow Grades > Customization Basics (https://submitty.org/instructor/course_settings/rainbow_grades/customization_basics)
=> [Documentation:RainbowGrades] Finish Customization Basics

_docs/developer/developing_the_php_site/view.md
This  documentation goes over how to make a page using the new Vue.js functionality provided in https://github.com/Submitty/Submitty/pull/10715.
This documentation is added to the bottom of `/developer/developing_the_php_site/view`, and details creating a new Vue page from scratch and showing how to tell a PHP View to serve it using `renderVue`.
=> [Documentation:Developer] Add documentation about pages in Vue

_docs/developer/getting_started/commit_to_PR_from_fork.md
**Summary:**
Added a small warning in the "Commit to PR from fork" page that tells developers to ensure that their git credentials are set before pulling and pushing from forks. If credentials are not set, then some commands will fail. This change would help newer developers who might not be proficient with git.
**Testing**
- Verified that changes appeared on the page
- Format looks good
=> [Documentation:Developer] set git credentials working with forks

_docs/sysadmin/installation/index.md
- Added a new section under NGINX configuration to explain how to set up a custom websocket port.
- Included steps to modify the `submitty.json` file and update the `proxy_pass` directive in the NGINX configuration.
- Clarified default behavior if the `websocket_port` field is not set.
- Previously, the documentation lacked details for configuring custom websocket ports after #6814 was merged. 
- An issue was created on [here](https://github.com/Submitty/Submitty/issues/6813). Fixes #6813
- Helps users avoid conflicts when running multiple instances or using different environments.
- Added a new "Configure Websocket Port" section to the NGINX setup documentation.
- Provided clear step-by-step instructions and examples.
- Documentation changes only, no code changes. 
- Verified formatting …
=> [Documentation:System] Added documentation for configuring custom websocket port in NGINX

_docs/developer/troubleshooting/installation_troubleshooting.md
Developer > Development Troubleshooting > Installation Troubleshooting currently informs developers that delays in `vagrant up` may be solved by opening the VirtualBox terminal GUI. This PR extends this fix to delays across the VM environment.
=> [Documentation:Developer] Add reminder to keep VM terminal open

_docs/developer/getting_started/vm_install_using_vagrant.md
The developer instructions for VM install include a link to VirtualBox version 6.1, but 7.1 is now compatible with Vagrant. 6.1 is no longer supported and Windows security updates may be causing issues.
The link leads to VirtualBox 6.1
The link leads to the latest version of VirtualBox.
=> [Documentation:Developer] update VirtualBox link

_docs/instructor/assignment_preparation/index.md, _docs/instructor/assignment_preparation/upload_gradeable.md, _docs/instructor/course_settings/rainbow_grades/customization_basics.md
Small updates related to gradable preparation examples. The current examples display `Homework` as a viable syllabus bucket option, but the backend expects `homework`. This is associated with the upcoming updates in https://github.com/Submitty/Submitty/pull/11544.
=> [Bugfix:InstructorUI] Valid Gradeable Syllabus Bucket Examples

_docs/developer/testing/linting_static_analysis.md
PR  [#9918](https://github.com/Submitty/Submitty/pull/9918) added two new aliases to `submitty_test,` `js-lint` and `css-lint`. This PR is documenting the scripts on the **Linting / Static Analysis** page.
=> [Documentation:Developer] Add new lint scripts to docs

_docs/instructor/course_settings/rainbow_grades/automatic_setup.md
The Rainbow Grades automatic setup instructions have not been updated since the Grade Reports page was removed.
Updated instructions and made slight improvements for grammar and consistency.
=> [Documentation:RainbowGrades] Update automatic setup instructions

_docs/developer/development_instructions/index.md
Suggestion from https://github.com/Submitty/Submitty/pull/11698
Add in some documentation for recreating courses. We added some new flags and courses.
=> [Documentation:Developer] Recreating Courses Documentation

_docs/developer/getting_started/vm_install_using_vagrant.md
I was previously unable to vagrant up from box because I thoughtlessly downloaded the I686 version from vagrant, thinking that AMD64 was incompatible with my Intel CPU (silly, I know). This PR gives more detailed instructions for what exactly to download for Windows users.
=> [Documentation:System] Improve Windows installation details

_docs/developer/testing/install_php.md, _docs/developer/testing/linting_static_analysis.md, _docs/developer/testing/php_unit_tests.md, _docs/sysadmin/installation/version_notes/v20.08.00.md
It turns out that no one knows how to run the full php unit test suite and have it pass, so I investigated the php unit test instructions and Improved them. @lavalleeale has some changes at [https://github.com/Submitty/Submitty/pull/11802](url) to allow for the full suite to pass so these docs should match that.
=> [Documentation:Developer] Improve php unit test instructions

_docs/developer/development_instructions/migrations.md
Small typo I discovered while reading up on migrations.
Changed `migraitons` to `migrations`
=> [Bugfix:Developer] Fixed Migrations Page Typo

_docs/student/communication/markdown.md
There previously were not any docs explaining adding equations to markdown after the feature was added in https://github.com/Submitty/Submitty/pull/11931. This PR adds docs explaining how to embed an equation in any markdownarea on Submitty.
=> [Documentation:Forum] Add markdown equation docs
