_docs/instructor/assignment_configuration.md, _docs/instructor/static_analysis.md
(Contributes to Submitty/Submitty#541)
=> Add documentation for static analysis

_docs/instructor/tree_tool.md
=> added tree tool page

_docs/sysadmin/student_auto_feed.md
Update documentation to match latest version.
Fix error in table of contents.
=> Student Auto Feed Documentation Update

_docs/sysadmin/git.md
In conjunction with Submitty/Submitty#1904.
=> Update git documentation

_docs/instructor/assignment_configuration.md
Added documentation for specifying docker networks
=> Added documentation for specifying docker networks

_docs/sysadmin/installation.md, _docs/sysadmin/server_os.md, _docs/sysadmin/student_auto_feed.md
Updated some sysadmin docs with Ubuntu 18.04 in mind.
=> Documentation Update

_docs/sysadmin/system_customization.md
Documentation for Submitty/Submitty#3249 per @bmcutler's comment
=> Add details on setting the system_message

_docs/index.md
The [Suggestions for New Developers] link on the Welcome page
=> Fix broken link

_docs/developer/migrations.md
=> Update docs for how migration tool works

_docs/sysadmin/installation.md
Closes Submitty/Submitty#3357 adding warning about umask change.
=> Add note about umask

_data/links.yml, _docs/instructor/premade_assignments.md
Redid all screenshots for student sections. All have same names as before, but now have the correct UI.
=> Updated all screenshots on student section

_docs/instructor/log_files.md
=> Update logs documentation and move under instructor (#59)

_data/links.yml, _docs/developer/updating_dependencies.md
Write-up of the various ways we handle dependencies within Submitty and how they are updated (or not).
Closes Submitty/Submitty#3346
=> Add documentation on how to manage Submitty's dependencies

_docs/developer/vm_install_using_vagrant.md
Modified the wording to make it more clear that executing these commands will remove all virtual machines (not only the ones associated with Submitty).
=> Modified wording on devel VM install page

_data/links.yml, _docs/sysadmin/email_configuration.md
Includes trouble shooting information
=> Document email configuration

_docs/developer/interface_design_style_guide.md
Repaired broken link (link worked OK in Jekyll, but not OK online).
=> Accessibility quickfix

_docs/developer/interface_design_style_guide.md
Updated File: _docs/developer/interface_design_style_guide.md
Removed "TL;DR" section about accessibility, as requested.
=> Removed "TL;DR" section about accessibility, as requested.

_docs/developer/phpstorm.md
Closes #3699
This PR modifies the phpstorm developer documentation on submitty.org  It contains new path mappings for phpstorm configuration that should work correctly with the vagrant VM in all cases.
=> Update PhpStorm documentation

_docs/developer/end_to_end_tests.md, _docs/developer/vm_install_using_vagrant.md
This PR add a note to the end to end testing page.
=> Add note to end to end

_data/api_data.json, _data/links.yml, _docs/developer/api/authentication.md, _docs/developer/api/courses.md, _docs/developer/api/index.md, _layouts/api.html
Addresses https://github.com/Submitty/Submitty/issues/3959 .
It is not pretty ~at all~ enough, but it contains necessary information.
Endpoints included are all endpoints working in `master`. Safe to merge.
=> Documentation for API

_docs/instructor/assignment_configuration/validation.md
Adds documentation for python custom validators. 
Related to main repository PR Submitty/Submitty#4027.
=> Add Documentation for Python Custom Validators

_docs/sysadmin/installation.md
=> Fix bootstrap run line to not mess up stdin

_docs/developer/router.md
Modify router documentation to reflect some recent changes.
=> Update router documentation

_docs/developer/router.md
To be merged after https://github.com/Submitty/Submitty/pull/4242
=> Update router doc after cleanup

_docs/developer/google_summer_of_code/2019_XiaoHan.md
I found it very hard to summarize PRs.. :sweat_smile:
=> [WIP][GSoC] 2019 GSoC report of Han

_docs/sysadmin/course_creation.md
To reflect changes brought by https://github.com/Submitty/Submitty/pull/4322
=> Rename adduser.py to adduser_course.py

_docs/developer/google_summer_of_code/2019_AnubhavSingh.md
My work over the period of GSoC 2019 compiled into a report. Looking for feedback if any!
=> [GSoC] 2019 GSoC report from Anubhav

_docs/sysadmin/student_auto_feed.md
Update student auto feed documentation as related to PR Submitty/SysadminTools#18
=> Update To Student Auto Feed Documentation

.travis.yml
This is a quick setup of travis for validating that the docs are buildable for a given PR/master. I will migrate this to buildbot sometime next week, but want the Travis build to act as a point of reference for that.
=> add basic travis job for checking jekyll syntax of docs

_docs/sysadmin/installation.md
https://submitty.org/sysadmin/installation - Server OS page - 
https://submitty.org/sysadmin/server_os does not workl.
=> Fixed broken link on installation

_docs/instructor/student_photos.md
Update documentation for Submitty/Submitty#4529
Companion PR to Submitty/Submitty#4530
=> [Documentation:StudentImages] Update allowed image types for student image upload

_docs/sysadmin/database_overview.md
=> Fix psql to import DB

_docs/instructor/managing_enrollment.md
Filled in the todo item explaining how to set PamAuth to DatabaseAuth
=> Change password

_docs/developer/vm_install_using_vagrant.md
After this pr you must use localhost to view submitty
https://github.com/Submitty/Submitty/commit/7a32e7776738bf922c2c95d0ef85ea65064b82df
This updated the url in the docs to the correct url
=> [System] Switched url to localhost

_docs/developer/interface_design_style_guide/web_accessibility.md
Updates to web accessibility guidelines.
=> [VPAT] Accessibility Guidlines Update

_layouts/default.html, css/main.scss, scripts/main.js
Fixed the errors and contrast issues
=> [VPAT:Documentation] fixed errors and contrast

_docs/developer/how_to_contribute.md
Added instructions on the steps to create a new branch from a PR and use that to test code from forks of the main Submitty repo. Also included a line of how to check out a branch the main repo as well for completeness
=> [Documentation:Contributing] Added instructions on testing PRs from forked repos

_docs/sysadmin/course_creation.md
Update create course link from  - https://github.com/Submitty/Submitty/blob/master/bin/create_course.sh > to 
https://github.com/Submitty/Submitty/blob/master/sbin/create_course.sh
=> Update create_course.sh link

_data/links.yml, _docs/developer/developing_the_php_site/feature_flags.md
Split apart from #187 so that it could be better self-contained within the review cycle for this feature, and not about the other pages.
Sibling PR: Submitty/Submitty#4954
=> Add documentation on how feature flags work

_docs/developer/project_ideas.md
+ Changed Publications link in GSoC Page.
=> [Documentation] Fix broken links to publications on projects page

_docs/index.md
This is also present on the GSoC landing page for Submitty.
=> [Documentation] Fixing quotes on index

_docs/developer/router.md
Sibling PR for changes introduced in Submitty/Submitty#5206.
=> [Documentation] Update documentation for the MultiResponse object

_docs/instructor/assignment_configuration/validation.md
Updated python custom validator documentation to reflect recent changes.
=> Update to python custom validator documentation

_docs/index/features.md
=> [Docs] Update notes on Features list

_docs/developer/phpstorm.md
The instructions for setting up PHPStorm have been updated to match the current release of PHPStorm.
=> [Documentation] Updating PHPStorm Set Up instructions

_docs/developer/interface_design_style_guide/web_accessibility.md
Adds a line to explain how to use the validate html button found in https://github.com/Submitty/Submitty/pull/5395
=> [Docs] Update for new Validate HTML button

_docs/developer/how_to_contribute.md
Make explicit the request to test and document all available themes (light mode/dark mode/black mdoe) for web accessibility/compliance when making UI changes.
=> [Documentation] Test all available themes

_data/links.yml, _docs/developer/developing_the_php_site/websocket.md, _docs/sysadmin/version_notes/v20.05.01.md, _docs/sysadmin/version_notes/v20.06.00.md
Documentation PR for Submitty/Submitty#5205.
=> [Documentation] add basic usage docs on websocket interface

_data/links.yml, _docs/developer/development_instructions/router-response.md
New developers typically ask questions about how the front end connects to the backend.
Our use of PHP annotations to define routes  can be a confusing concept.
Also adds information on different response types and what developers should be using
=> [Documentation:Developer] routes and MultiResponse object

_docs/developer/vm_install_using_vagrant.md
Made changes to the "virtualization" section in vm_install_using_vagrant.md file, which deals with setting up a local instance of Submitty. 
- Changed formatting virtualization setup section.
- Added more comprehensive instructions for accessing BIOS and setting up virtualization on Windows.
- Added links to guides on BIOS setup and virtualization setup.
- Removed image from Windows virtualization guide that caused clutter and was unneccesary.
=> Changed Virtualization section.

_docs/developer/development_instructions.md, _docs/developer/how_to_contribute.md, _docs/developer/index.md, _docs/developer/vm_install_using_vagrant.md
Added more troubleshooting hints before VM installation begins.
Broke the installation page into sections.
Revised the structure of the code development update page (and removed some bulk).
Added instructions to vagrant up without sample submissions.
=> [Documentation:Developer] Installation & Development Instructions

_docs/instructor/assignment_configuration/notebook.md, _docs/sysadmin/system_customization.md
Updates the notebook syntax page to contain information on the sytanx for adding file submission areas.
=> Update Notebook syntax to include file_submission

_docs/instructor/assignment_configuration/notebook.md
from @gregory-bauer
resolving conflicts in PR #238
(Apologies, I could not figure out how to either save conflicts resolved through the github web editor nor to push to your fork.  Permissions errors, github bug, or my error?)
=> [Documentation:Developer] Ruby/GIT Installation

_docs/developer/development_instructions/router-response.md, _docs/developer/router.md
documentation PR for issue Submitty/Submitty#5388 and PR Submitty/Submitty#5534
=> [Documentation] Add /courses/ prefix to course urls for router

_docs/developer/development_instructions/router-response.md
This PR updates the documentation to remove functions deprecated in https://github.com/Submitty/Submitty/pull/5576
Minor grammer and markdown fixes as well to the page.
=> Router-Response documentation update

_data/links.yml, _docs/developer/google_summer_of_code/2018_TusharGurjar.md, _docs/index/contact.md, _docs/index/tutorial.md, _docs/instructor/assignment_configuration/structure.md
=> Revise "Welcome" section

security.txt
=> Add security.txt file

_docs/developer/development_instructions.md
Sister PR to Submitty/Submitty#5620
=> Add line about no_submissions flag for recreate_sample_courses script

_docs/developer/migrations.md
Sister comment to Submitty/Submitty#5392
=> Update migrator step to update sql files to use dump command

_docs/sysadmin/installation.md
Updates the documentation to include a bit of words for the DB port, as well as updates the description of installing postgresql.
Related to Submitty/Submitty#5616
=> Update documentation on installing postgresql

_data/links.yml, _docs/developer/development_instructions/merge_conflicts.md
documentation for new developers on how to resolve merge conflicts with php composer package manager files.
=> [Documentation:Developer] resolving merge conflicts

_data/links.yml, _docs/developer/worker_vm.md
Instructions to create one or more "worker" virtual box VMs for development
=> [Documentation] instructions to make a worker vm for development

_docs/developer/coding_style_guide/javascript.md, _docs/developer/testing/index.md, _docs/developer/testing/linting_static_analysis.md
Documentation PR for Submitty/Submitty#5453
=> [Documentation] js style guide

_docs/developer/development_instructions.md
Add information about Twig cache.
=> Update Development Instructions

_docs/developer/google_summer_of_code/2020_Harsh_Joshi.md
=> Introduce GSOC Report - Harsh Joshi

_docs/sysadmin/system_customization.md
=> [Documentation:SysAdmin] tune php configuration

_docs/developer/testing/index.md, _docs/developer/testing/site_end_to_end_tests.md
Updating some instructions for running E2E tests
=> [Documentation:Developer] Updating E2E instructions

Gemfile.lock, _docs/developer/ms_phd_students/MS_2020_John_Hulton.md
The images for the page developer/ms_phd_students/MS_2020_John_Hulton are not showing up. This is a quick fix to make the images show up.
=> Fixing Peer Images

_docs/sysadmin/update.md
Reflects what was implemented by Submitty/Submitty#5896
=> [Documentation:System] Updates the reload option during reinstall

_data/links.yml, _docs/instructor/submini_polls.md
Added a page in the Instructor section detailing how to enable and use the Submini polling system
=> [Documentation:Instructors] Submini Polling Documentation

_docs/developer/how_to_contribute.md
Documentation for the workflow added in Submitty/Submitty#6099
=> [Documentation:Developer] Add description of PR title workflow

.github/workflows/pr_title.yml, _docs/developer/how_to_contribute.md
originally grouped under InstructorUI:
SubminiPolls, HelpQueue, CourseMaterials, Plagiarism
also add pr title tester (just copied from Submitty/Submitty repo)
=> [Documentation:Developer] add 4 new PR title modules

_data/api_data.json, _docs/developer/database_design.md, _docs/developer/pgadmin.md, _docs/developer/phpstorm.md, _docs/developer/router.md, _docs/developer/worker_vm.md
Docs PR for Submitty/Submitty#6220
=> [Refactor:System] Update URL to use for vagrant

_docs/sysadmin/installation.md
To help new installers better understand what they need to enter.
=> [Documentation:System] Add explanations to config options

_docs/developer/testing/index.md
Sibling commit to https://github.com/Submitty/Submitty/pull/6296
=> [Documentation:Developer] Pin version of sqlalchemy

_docs/developer/updating_dependencies.md, _docs/instructor/assignment_configuration/overview.md, _docs/instructor/assignment_configuration/validation.md, _docs/sysadmin/dependencies.md
Documentation PR for Submitty/Submitty#6283.
=> [Documentation:System] Remove mention of emma

_docs/developer/vm_install_using_vagrant.md
PR for outlining the steps for testing with a remote device as described in Submitty/Submitty#6326.
=> [Documentation:Developer] Remote Device Testing Docs

Gemfile, Gemfile.lock, _data/links.yml, _docs/developer/developing_the_php_site/controller.md, _docs/developer/developing_the_php_site/controllers.md, _docs/developer/developing_the_php_site/index.md, _docs/developer/developing_the_php_site/model.md, _docs/developer/developing_the_php_site/view.md, _docs/developer/developing_the_php_site/views.md, _docs/developer/development_instructions.md
Originally written by @emaicus.
Initial work to add to submitty.org by @rolandrao in PR #323 (this PR replaces).
=> [Documentation:Developer] Model-View-Controller Example

_docs/developer/vm_install_using_vagrant.md
Improve documentation for connecting to a Vagrant instance of Submitty with a remote device.
=> [Documentation:Developer] Improve remote device documentation

_docs/developer/migrations.md
Re-ordered one of the steps for a creating a migration that was no longer necessary.
=> [Documentation:Developer] Re-ordering migration steps.

_docs/student/communication/forum.md
Updates documentation for discussion forum to reflect new background color for unread posts/threads in dark/black mode.
=> [Documentation:Forum] Update Forum Dark Mode Documentation

_data/api_data.json, _docs/developer/database_design.md, _docs/developer/developing_the_php_site/websocket.md, _docs/developer/pgadmin.md, _docs/developer/phpstorm.md, _docs/developer/router.md, _docs/developer/testing/cypress.md, _docs/developer/vm_install_using_vagrant.md, _docs/developer/worker_vm.md, _docs/sysadmin/course_creation.md, _docs/sysadmin/installation.md, _docs/sysadmin/server_os.md, _docs/sysadmin/system_customization.md, _docs/sysadmin/worker_installation.md
Ubuntu 20.04 our current default/recommended server version.
=> [Documentation:System] update for Ubuntu 20.04

_docs/developer/testing/linting_static_analysis.md
PR https://github.com/Submitty/Submitty/pull/6630 was created and merged but I forgot to update this part of the documentation with instructions about how to run it from the command line.  That has been added in this PR.
=> [Documentation:Developer] Add CSS linting documentation

_docs/developer/plagiarism.md
PR https://github.com/Submitty/Lichen/pull/40 introduces a few preliminary tests for Lichen.  This PR adds documentation regarding how they should be run.
=> [Documentation:Plagiarism] Add Lichen test docs

_docs/developer/plagiarism.md
Updates the Lichen Developer documentations for the feature added in https://github.com/Submitty/Submitty/pull/6867
=> [Documentation:Developer] Install_lichen script alias

_docs/developer/rpi_summer_rcos/2021_Shelly_Belsky.md
=> [Documentation:Developer] Summer work writeup

_docs/instructor/course_management/plagiarism.md
This PR adds documentation for the changes added in https://github.com/Submitty/Lichen/pull/56.
=> [Documentation:Plagiarism] Add subtractive regex docs

_docs/instructor/autograding/docker_ui.md, navtreedata.js
Added documentation on the Docker UI page under instructor autograding.
=> [Documentation:Autograding] Docker UI documentation

_docs/developer/rpi_summer_rcos/2021_Henrik_Lam.md
Added documentation of what I did during the summer 2021
=> [Documentation:Developer] Documentation of contribution summer2021

_docs/developer/vm_install_using_vagrant.md
Add notes about upgrading/reinstalling virtualbox & vagrant on Mac.
=> [Documentation:System] Upgrant Mac allow access

_docs/sysadmin/installation.md, _docs/sysadmin/system_customization.md
Add reminder to configure & test NTP - Clock Synchronization
=> [Documentation:System] Installation notes for NTP

_docs/developer/developing_the_php_site/controller.md
Documentation PR for https://github.com/Submitty/Submitty/pull/7217
=> [Documentation:System] Add docs on disabling a controller

_docs/instructor/course_management/managing_enrollment.md
Updates documentation for Managing Enrollment CSV uploads. Paired with [Submitty change PR #7284](https://github.com/Submitty/Submitty/pull/7284) to simplify upload modals.
=> [Documentation:InstructorUI] Graders CSV Upload

_docs/developer/xdebug.md, navtreedata.js
Add additional documentation for Xdebug debug and profiling.
=> [Documentation:Developer] Add more documentation for Xdebug

_docs/developer/testing/linting_static_analysis.md
This PR adds documentation on updating the phpstan baseline if someone fixes one of the intentionally ignored errors.
=> [Documentation:Developer] Update baseline for phpstan

_layouts/default.html
=> [Documentation:Developer] Update year in footer

_docs/developer/project_ideas.md
Fixes a link and corrects a wording.
=> [Documentation:Developer] Update project ideas

_docs/sysadmin/version_notes/v22.02.01.md, _docs/sysadmin/version_notes/v22.03.00.md, navtreedata.js
Documentation PR for https://github.com/Submitty/Submitty/pull/7676
=> [Documentation:System] Add routing flexibility install notes

_docs/developer/rensselaer_center_for_open_source/2021_William_Allen.md
I forgot to finish my summer writeup in the fall so I am now creating this PR with a more complete version of a draft I had.
=> [Documentation:Developer] Finish summer 2021 writeup

_docs/sysadmin/installation/system_customization.md
This PR adds related documentation for https://github.com/Submitty/Submitty/pull/7813.
=> [Documentation:System] Markdown Login Screen Customization

_docs/sysadmin/installation/version_notes/v22.05.00.md, navtreedata.js
Adds sysadmin action notes for https://github.com/Submitty/Submitty/pull/7859
=> [Documentation:System] Add websocket bugfix install notes

_docs/sysadmin/troubleshooting/system_debugging.md
Adds documentation for https://github.com/Submitty/Submitty/pull/7890
=> [Documentation:System] Websocket Error Logging

_docs/developer/testing/linting_static_analysis.md
Updates documentation on running phpstan after PR https://github.com/Submitty/Submitty/pull/7917
=> [Documentation:Developer] Update phpstan dev command

_docs/developer/development_instructions/index.md
revise development instructions overview page
=> [Documentation:Developer] development instructions overview

_docs/instructor/autograding/validation.md
=> [Documentation:Autograding] Add markdown label for json blocks

_docs/sysadmin/installation/version_notes/index.md, _docs/sysadmin/installation/version_notes/v22.06.00.md, navtreedata.js
Documentation for Submitty/Submitty#8031
=> [Documentation:System] v22.06.00 release notes

_docs/sysadmin/installation/version_notes/v22.06.00.md
Add a note for the v22.06.00 release.
=> [Documentation:System] pg_hba.conf file

_docs/instructor/autograding/static_analysis/index.md
=> [Documentation:Autograding] Add comment_count command

_docs/developer/google_summer_of_code/2022_Madhur_Jain.md
Report for the work done during summers of 2022 under Google Summer of Code.
=> [Documentation:Developer] Summer Report Madhur

_docs/developer/development_instructions/miscellaneous.md, _docs/sysadmin/configuration/saml_authentication.md
Updates Sysadmin and Developer SAML docs.
=> [Documentation:System] Update SAML docs

_docs/developer/development_instructions/performance_testing.md, navtreedata.js
This adds docs about xdebug and apache bench for performance testing.
=> [Documentation:System] Performance Testing

_docs/developer/rensselaer_center_for_open_source/2022_Evan_Bowen_Shi.md
Added the end-of-summer report for Evan Shi.
=> [Documentation:Developer] Summer Report - Evan Shi

_docs/developer/rensselaer_center_for_open_source/2022_Thomas_Kozlowski.md
My report of what I worked on during summer 2022.
=> [Documentation:Developer] Summer Report - Thomas Kozlowski

_docs/developer/google_summer_of_code/2022_Akshat_Batra.md, _docs/student/account/authentication_tokens.md
[Submitty/Submitty#8284](https://github.com/Submitty/Submitty/pull/8284) changes the location of "Authentication Tokens" button.
=> [Documentation:Submission] Update authentication tokens docs

_docs/developer/rensselaer_center_for_open_source/moorthy.md, _docs/sysadmin/installation/system_customization.md
and also bug fix path to moorthy duck.
=> [Documentation:System] tweak system customization

_docs/developer/development_instructions/performance_testing.md
Adds documentation on viewing, running, and visualizing SQL queries.
=> [Documentation:System] Add SQL query performance testing docs

_docs/developer/rensselaer_center_for_open_source/2022_Jerry_Jiarui_Lu.md
End-of-~~summer~~winter report...
=> [Documentation:Developer] Summer Report - Jerry Lu

_docs/developer/getting_started/vm_install_using_vagrant.md
Added more common issues in the troubleshooting part of 'Getting Started'. Also updated to show the updated final message.
message changed in Submitty/Submitty#8923
=> [Documentation:System] final install message & troubleshooting

_docs/sysadmin/installation/system_customization.md
Updated PHP-FPM documentation to add static configuration details and the PHP-FPM process manager calculator.
=> [Documentation:System] Update PHP-FPM documentation

_docs/developer/google_summer_of_code/index.md, _docs/index/publications.md, _docs/sysadmin/configuration/saml_authentication.md
some downloads had the word master rather than main
=> [Bugfix:Developer] Change master to main

_docs/developer/getting_started/vm_install_using_vagrant_apple_silicon.md
Add the sample installation success message to the ARM Mac Vagrant instructions page.
=> [Documentation:Developer] ARM Mac Duck

_docs/developer/getting_started/vm_install_using_vagrant.md
Submitty users table doesn't show limited access grader (mentor) login
Added table entry for limited access grader and made the role values more specific
=> [Documentation:Developer] Added grader to list of vm users

_docs/developer/development_instructions/troubleshooting.md, _docs/developer/getting_started/vm_install_using_vagrant.md, _docs/developer/getting_started/vm_install_using_vagrant_apple_silicon.md
Closes Submitty/Submitty#9374
Adds documentation for overriding default forwarded ports through environment variables.
=> [Documentation:Developer] Vagrant Port Override Env Vars

README.md
Added small detail in README on a possible hangup when installing bundle.
=> [Documentation:Developer] Added bundle troubleshooting advice

README.md
Added a note in the README.md that has the instructions for running Jekyll locally to generate and view the webpages.  The note addresses a possible bug that some OS might encounter if running the most recent version of Ruby.
=> [Documentation:Developer] Bundle install Error Fix

_docs/developer/software_and_system_design/coding_style_guide/php.md
The bottom of php.md looks like this:
Added the last back tick to make it work properly
=> [Bugfix:Developer] formatting error

README.md
One bullet point had incorrect italics. This PR fixes the italics while adding additional installation information.
=> [Documentation:Developer] Fix italics in readme

_docs/developer/getting_started/vm_install_using_vagrant.md
This is the Error that occurs with people outside USA.
=> [Documentation:Developer] InstallationTroubleshooting VPN Problem

_docs/developer/getting_started/vm_install_using_vagrant_apple_silicon.md, _docs/developer/getting_started/worker_vm.md, navtreedata.js
Updated the automated worker vm installation docs for the new multi-worker setup.
=> [Documentation:Developer] Updated worker vm documentation

_docs/developer/rensselaer_center_for_open_source/2023_Nia_Heermance.md
=> [Documentation:Developer] Nia Summer Report

_docs/student/communication/markdown.md
New content:
Bold and Italics (at the same time)
Headings
Improved Content:
Code blocks (shows syntax highlighting)
Lists (Shows sub-items)
=> [Documentation:Forum] Added More information to Markdown page

_docs/instructor/assignment_configuration/configuration_path.md, _docs/instructor/course_settings/rainbow_grades/customization_basics.md
=> [Documentation:Developer] remove iclicker

_docs/developer/rensselaer_center_for_open_source/2021_Chris_Reed.md
While writing summer report, tried to see how others did it. Saw trivial typo..
=> [Documentation:Developer] Typo-fix

Gemfile.lock, _docs/developer/development_instructions/trigger_functions.md, navtreedata.js
There is now documentation on how to create trigger functions and edit existing functions.
=> [Documentation:Developer] Add Trigger Function Documentation

_docs/instructor/course_settings/rainbow_grades/manual_setup.md
add description for drop lowest gradeable.
In future we need to add support from GUI to drop lowest 
Closes Submitty/Submitty/issues/9878
=> [Documentation:InstructorUI] add drop lowest description

Gemfile.lock, README.md, _docs/developer/getting_started/project_ideas.md, _docs/developer/google_summer_of_code/index.md
update for GSOC 2024 announcement
=> [Documentation:Developer] update for GSOC 2024 announcement

_docs/developer/getting_started/vm_install_using_vagrant.md
Previously the documentation did not clarify that any user may be logged in as by using their User ID as both their username and password. This clarifies that ability and gives an easy way to look up a list of users.
=> [Documentation:Developer] Log-in instructions for any user

_docs/instructor/autograding/docker_ui.md
=> [Documentation:Developer] Typos on Docker UI

_docs/instructor/autograding/docker_images.md
=> [Documentation:Developer] Fix docker typo

_docs/developer/google_summer_of_code/2024_Rahul_Vishwakarma.md
Final Report of my work as GSoC contributor
=> [Documentation:Developer] Rahul GSoC Report

_docs/developer/rensselaer_center_for_open_source/2023_Satvik_Karanam.md
=> [Documentation:Developer] Satvik Summer Report

_docs/student/account/email_addresses.md
=> [Documentation:InstructorUI] Fix email address typo

_docs/instructor/course_management/managing_enrollment.md, _docs/student/account/index.md
This PR adds documentation for https://github.com/Submitty/Submitty/pull/10778, which adds the ability for users to register for courses if the instructor enables it in the Course Settings page.
=> [Documentation:System] Docs for Self Registration Courses

_docs/developer/getting_started/make_a_pull_request.md
With the addition of the new feature Live Chat, we should allow Live Chat as a title module so that new PRs relating to it are better organized. See action-pr-title PR here: [https://github.com/Submitty/action-pr-title/pull/13](url)
=> [Documentation:Developer] Add LiveChat to the forum module

_docs/sysadmin/installation/version_notes/v25.07.01.md
Add 'bash' to version notes for v25.07.01.
https://submitty.org/sysadmin/installation/version_notes/v25.07.01
=> [Bugfix:Installation] bash command for version notes
